### ISSUE TITLE
What does it do?

### ISSUE THREAD

**Issue by mindplay-dk** [swordev/phpstan-vscode#1]
I've tried every other phpstan extension, and decided to try this as well.

It doesn't seem to do anything? Nothing shows up in the problems panel.

There's no description in the README, so I don't know if that's what it was supposed to do?

(Any particular reason you're starting over? There are 3 other extensions plus a couple of forks already. None of them provide a really good experience, but the best I've found thus far is [this one](https://github.com/breeze2/vscode-phpstan) - it just has [this](https://github.com/breeze2/vscode-phpstan/issues/14#issuecomment-729736292) annoying issue...)

**Comment by juanrgm** [comment]
Hi @mindplay-dk,

> There's no description in the README, so I don't know if that's what it was supposed to do?

You must have a valid `phpstan.neon` file on the root dir of the project and phpstan installed locally (`composer require phpstan / phpstan --dev`), then the extension will detect it and simply it will run `phpstan analyse` on every file change.

> (Any particular reason you're starting over? There are 3 other extensions plus a couple of forks already. None of them provide a really good experience, but the best I've found thus far is this one - it just has this annoying issue...)

This is the only extension that have file watcher, and as you say, I also had bad experiences with other extensions.

Thanks for the feedback!

**Comment by juanrgm** [comment]
Hi again,

I updated the repository [README](https://github.com/swordev/phpstan-vscode/commit/5098b86ff75451582bfbda1276ada09ff55eb338), maybe it will help you.
