### ISSUE TITLE
Override config file location

### ISSUE THREAD

**Issue by jasonwilliams** [swordev/phpstan-vscode#10]
Hey @juanrgm great extension

My understanding is this extension will look in the project root for the PHPStan config file. We work in a monorepo and my neon file is in a subfolder.

Can there be an option to set where the neon file is? It looks like this isn't overridable currently.

You could add `configPath` to the [settings](https://github.com/swordev/phpstan-vscode/blob/main/src/extension.ts#L7-L16)

Then [findConfigPath()](https://github.com/swordev/phpstan-vscode/blob/d2d8c1ea3bfd6d221742c2f5f30dd6556c75828c/src/PHPStan.ts#L50) could take a path string as an argument and use that if it's provided. The path can be a relative path from the workspaceRoot, so you can just concatenate it onto `dir`.

**Comment by jasonwilliams** [comment]
ping @juanrgm

**Comment by juanrgm** [comment]
Closed via https://github.com/swordev/phpstan-vscode/commit/2819cd8a3f3b7ae1d13c35ebd0cd0ceb79cbdd3b and https://github.com/swordev/phpstan-vscode/commit/c4feb9489d1801f54f221fe4a616f9998637c989.
