### ISSUE TITLE
Multiple runs at the same time

### ISSUE THREAD

**Issue by driskell** [swordev/phpstan-vscode#11]
I unlocked my machine after a couple days of inactivity and my CPU was at 100% for a good 15 minutes. Turned out phpstan was running simultaneously about 5 times on a large project that was open.

<img width="330" alt="Screenshot 2022-07-11 at 10 05 07" src="https://user-images.githubusercontent.com/939815/178229512-f16a79c9-d009-4676-bbd1-8baa546d59b3.png">

Update:

Issue appears that each file event causes a full analyse rather than just for that file. For a larger project this can take some time. And I think for some reason as I resumed my machine the file watcher must've been behind a bit and I had caused a file to be saved 5 times and all 5 watch events occurred at exactly the same time, triggering 5 analyse commands on a large project.

I guess the solution is run only one analyse at any moment in time. If one needs to be run and one is in progress, queue a second one, but never queue any more. So eventually consistent error reports.

**Comment by juanrgm** [comment]
Closed via https://github.com/swordev/phpstan-vscode/commit/bc7f2ccbaff312badba00cb07c96bb62942fba9d.
