### ISSUE TITLE
not able to run inside docker

### ISSUE THREAD

**Issue by guifelix** [swordev/phpstan-vscode#4]
Tried using the extension on a project inside a docker container and was unable to do so. To double check if it was working, went to integrated terminal (inside container) and executed phpstan, everything was working fine... 

It might not be working also because the project is organized that way:

```
application
  ...
  phpstan.neon
build
  ...
nginx
  ...
```

So if possible it would be nice having a config to set the folder where the extension can find neon file

**Comment by juanrgm** [comment]
Closed via https://github.com/swordev/phpstan-vscode/commit/2819cd8a3f3b7ae1d13c35ebd0cd0ceb79cbdd3b and https://github.com/swordev/phpstan-vscode/commit/c4feb9489d1801f54f221fe4a616f9998637c989.
