### ISSUE TITLE
Unable to use phpstan relative paths

### ISSUE THREAD

**Issue by jleonardolemos** [swordev/phpstan-vscode#5]
I have some projects using PHPstan and some projects not using this, i dont have phpstan installed on my computer but a do have this inside vendor projects, I have tried:

```
${workspaceFolder}/vendor/bin/phpstan
```
and 

```
./vendor/bin/phpstan
``` 

Both these configurations did not worked.

Am i doing it wrong? Can I use relative paths?

**Comment by epyu-lee** [comment]
I installed the PHPStan.phar.  This works with 
"phpstan.path": "c:\\phptools\\phpstan.phar"

And my PHP is on my Windows PATH, as you would expect for windows:
"phpstan.phpPath": "php"

Of course, if you're relying on different version of PHPStan, you may need a stronger solution.

**Comment by juanrgm** [comment]
The correct path is `./vendor/phpstan/phpstan/phpstan`. I'm sorry for the wait.
