### ISSUE TITLE
Could not open input file: ./vendor/bin/phpstan

### ISSUE THREAD

**Issue by exbit** [swordev/phpstan-vscode#7]
![image](https://user-images.githubusercontent.com/1260469/121176230-a70f1380-c864-11eb-9f2e-58714ee85bd4.png)
![image](https://user-images.githubusercontent.com/1260469/121176545-01a86f80-c865-11eb-8ba3-61d3f9687fb7.png)
![image](https://user-images.githubusercontent.com/1260469/121177106-ad51bf80-c865-11eb-995e-6c7b718d3351.png)

**Comment by juanrgm** [comment]
The correct path is `./vendor/phpstan/phpstan/phpstan`. I'm sorry for the wait.

Maybe the `phpstan.path` setting description is confusing, I will change it.
