### ISSUE TITLE
Compatible with intelephense?

### ISSUE THREAD

**Issue by coccoinomane** [swordev/phpstan-vscode#8]
Hello!
While using your extension, would you recommend turning off [Intelephense](https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client)?
Or maybe configure it in a way so that errors are not double counted?
Thanks!
Cocco

**Comment by juanrgm** [comment]
Intelisense will be required for autocompletion and other LSP features (refactoring, find usages, ...).
