### ISSUE TITLE
Install experience

### ISSUE THREAD

**Issue by epyu-lee** [swordev/phpstan-vscode#9]
Thank you for creating this tool.  I appreciate the effort you've gone to.  This bug report outlines my install experience and you may wish to break into several bugs or, of course, do as you will!  I'm able to use the tool, but as I say in the last section, the file watcher part still isn't working for me.

Diagnoses of problems with this plugin was difficult as the error messages weren't clear.  The meaning of some messages became more clear after seeing what success looked like.  Likewise, just a little more text documenting the meaning of the options would help!  "Config File Watcher Basenames" seemed particularly obscure.  "PHPStan Config File <something>" would have been better.

Once I understood the reason that the config file wasn't being read, things got easier.  I have a multiroot workspace with the PHPStan config at one of the roots--once I put an PHPStan config include in the workspace directory, it started reading the config file.  I think I would prefer to be able to specify the PHPStan config file path, but at least that got me more in business.  This was with v1.4.4

This is what I see with it working normally:
```
# Config:
null
# Command: analyse
Note: Using configuration file C:\[snip!]
```
Remove the main phpstan.neon.dist and I see when doing "Resume file watcher":
```
# Command: analyse
At least one path must be specified to analyse.

# Spawn error
Unexpected end of JSON input
```

I'd expect something more helpful, like "No config file found, including at ${workspaceFolder}/phpstat.neon.dist"

For some reason, VS Code doesn't want to update to v1.4.6.  "Install another version..." lets me select 1.4.6 but then does nothing.  There's no "Update" button I can see. Restarting VS Code twice got me updated.  Maybe that's normal.

At this point the plugin still does not run as a file watcher.  I have default settings, including the 200mS "Analysed Delay".  
* Invoke PHPStan: Resume file watcher
* Observe output showing PHPStan ran.
* Introduce a logic error (Depend on undefined variable) and save
* Wait, and observe no PHPStan run; no change to error display.
* Again invoke PHPStan: Resume file watcher
* Observe expect run and new error display.
* repeat: remove error, save, no change, reinvoke, observe run and change.

[edited to clean up markdown.]

**Comment by juanrgm** [comment]
Closed via https://github.com/swordev/phpstan-vscode/commit/2819cd8a3f3b7ae1d13c35ebd0cd0ceb79cbdd3b and https://github.com/swordev/phpstan-vscode/commit/c4feb9489d1801f54f221fe4a616f9998637c989.
